import pytest
import boto3
import os
import time
from typing import Generator

@pytest.fixture(scope="session")
def aws_credentials():
    """Mocked AWS Credentials for LocalStack."""
    os.environ["AWS_ACCESS_KEY_ID"] = "test"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "test"
    os.environ["AWS_SECURITY_TOKEN"] = "test"
    os.environ["AWS_SESSION_TOKEN"] = "test"
    os.environ["AWS_DEFAULT_REGION"] = "us-east-1"

@pytest.fixture(scope="session")
def localstack_endpoint():
    return os.environ.get("LOCALSTACK_ENDPOINT", "http://localhost:4566")

@pytest.fixture
def s3_client(aws_credentials, localstack_endpoint):
    """Create S3 client for LocalStack."""
    return boto3.client(
        "s3",
        endpoint_url=localstack_endpoint,
        region_name="us-east-1",
        aws_access_key_id="test",
        aws_secret_access_key="test"
    )

@pytest.fixture
def wafv2_client(aws_credentials, localstack_endpoint):
    """Create WAFv2 client for LocalStack."""
    return boto3.client(
        "wafv2",
        endpoint_url=localstack_endpoint,
        region_name="us-east-1",
        aws_access_key_id="test",
        aws_secret_access_key="test"
    )

@pytest.fixture
def sns_client(aws_credentials, localstack_endpoint):
    """Create SNS client for LocalStack."""
    return boto3.client(
        "sns",
        endpoint_url=localstack_endpoint,
        region_name="us-east-1",
        aws_access_key_id="test",
        aws_secret_access_key="test"
    )

@pytest.fixture
def kms_client(aws_credentials, localstack_endpoint):
    """Create KMS client for LocalStack."""
    return boto3.client(
        "kms",
        endpoint_url=localstack_endpoint,
        region_name="us-east-1",
        aws_access_key_id="test",
        aws_secret_access_key="test"
    )

@pytest.fixture
def iam_client(aws_credentials, localstack_endpoint):
    """Create IAM client for LocalStack."""
    return boto3.client(
        "iam",
        endpoint_url=localstack_endpoint,
        region_name="us-east-1",
        aws_access_key_id="test",
        aws_secret_access_key="test"
    )

@pytest.fixture
def cloudformation_client(aws_credentials, localstack_endpoint):
    """Create CloudFormation client for LocalStack."""
    return boto3.client(
        "cloudformation",
        endpoint_url=localstack_endpoint,
        region_name="us-east-1",
        aws_access_key_id="test",
        aws_secret_access_key="test"
    )

@pytest.fixture
def sample_server_hex():
    """Mock server hex value that would be generated by Terraform."""
    return "a1b2c3d4e5f6g7h8"

@pytest.fixture
def sample_uuid():
    """Mock UUID value that would be generated by Terraform."""
    return "12345678-1234-1234-1234-123456789012"

@pytest.fixture
def malicious_ip_samples():
    """Sample malicious IP addresses for testing WAF rules."""
    return {
        "ipv4": ["192.0.2.1/32", "198.51.100.2/32", "203.0.113.3/32"],
        "ipv6": ["2001:db8::1/128", "2001:db8::2/128"]
    }

@pytest.fixture
def waf_log_samples():
    """Sample WAF log entries for testing log processing."""
    return [
        {
            "timestamp": 1640995200000,
            "formatVersion": 1,
            "webaclId": "arn:aws:wafv2:us-east-1:123456789012:regional/webacl/ExampleWebACL/473e64fd-f30b-4765-81a0-62ad96dd167a",
            "terminatingRuleId": "DefaultAction",
            "terminatingRuleType": "REGULAR",
            "action": "ALLOW",
            "httpSourceName": "ALB",
            "httpSourceId": "123456789012-app/my-loadbalancer/50dc6c495c0c9188",
            "ruleGroupList": [],
            "rateBasedRuleList": [],
            "nonTerminatingMatchingRules": [],
            "httpRequest": {
                "clientIp": "192.0.2.1",
                "country": "US",
                "headers": [
                    {"name": "Host", "value": "example.com"},
                    {"name": "User-Agent", "value": "Mozilla/5.0 (compatible; BadBot/1.0)"}
                ],
                "uri": "/login",
                "args": "username=admin&password=admin",
                "httpVersion": "HTTP/1.1",
                "httpMethod": "POST",
                "requestId": "1-61c88654-7b30efab2b30efab2b30efab"
            }
        }
    ]